version: "3.8"
services:
  graphdb:
    image: neo4j:${NEO4J_IMAGE_TAG:-latest}
    restart: unless-stopped
    container_name: graphdb
    environment:
      NEO4J_AUTH: none
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - graphdb-data:/data
      - graphdb-logs:/logs
      - graphdb-import:/var/lib/neo4j/import
      # - ./plugins:/plugins # nb: wget "https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/5.4.0/apoc-5.4.0-extended.jar"
      - graphdb-plugins:/plugins
    networks:
      - graphdb-network

volumes:
  graphdb-data:
  graphdb-logs:
  graphdb-import:
  graphdb-plugins:

networks:
  graphdb-network:
    driver: bridge


